
// I wrote this code blocks a long ago and sorry for the bad format.
// When i wrote i barely knew jquery
// Feel free to edit and use
// © Kalana Hettiarachchi
// https://www.linkedin.com/in/kalanahe/


$(document).ready(function () {
            $("#district").change(function () {
                var val = $(this).val();
                if (val == "Colombo") {
                    $("#cityi").html("<option value=''></option><option value='Colombo'>Colombo</option><option value='Dehiwala'>Dehiwala</option><option value='Moratuwa'>Moratuwa</option><option value='Kotte'>Kotte</option><option value='Kolonnawa'>Kolonnawa</option><option value='Awissawella'>Awissawella</option><option value='Nugegoda'>Nugegoda</option><option value='Maradana'>Maradana</option><option value='Maharagama'>Maharagama</option><option value='Kaduwela'>Kaduwela</option><option value='Kesbewa'>Kesbewa</option><option value='Boralesgamuwa'>Boralesgamuwa</option><option value='Kotikawatta'>Kotikawatta</option><option value='Homagama'>Homagama</option><option value='Kottawa'>Kottawa</option><option value='Mattegoda'>Mattegoda</option><option value='Padukka'>Padukka</option><option value='Thimbirigasyaya'>Thimbirigasyaya</option><option value='Seethawaka'>Seethawaka</option>");
                } 
                else if (val == "Gampaha") {
                    $("#cityi").html("<option value=''></option><option value='Negombo'>Negombo</option><option value='Katunayake'>Katunayake</option><option value='Ja-Ela'>Ja-Ela</option><option value='Kelaniya'>Kelaniya</option><option value='Peliyagoda'>Peliyagoda</option><option value='Wattala'>Wattala</option><option value='Gampaha'>Gampaha</option><option value='Minuwangoda'>Minuwangoda</option><option value='Attanagalla'>Attanagalla</option><option value='Biyagama'>Biyagama</option><option value='Divulapitiya'>Divulapitiya</option><option value='Dompe'>Dompe</option><option value='Katana'>Katana</option><option value='Mahara'>Mahara</option><option value='Mirigama'>Mirigama</option>");
                } 
                else if (val == "Galle") {
                    $("#cityi").html("<option value=''></option><option value='Galle'>Galle</option><option value='Ambalangoda'>Ambalangoda</option><option value='Ahangama'>Ahangama</option><option value='Ahungalla'>Ahungalla</option><option value='Baddegama'>Baddegama</option><option value='Balapitiya'>Balapitiya</option><option value='Batapola'>batapola</option><option value='Bentota'>Bentota</option><option value='Elpitiya'>Elpitiya</option><option value='Habaraduwa'>Habaraduwa</option><option value='Hiniduma'>Hiniduma</option><option value='Hikkaduwa'>Hikkaduwa</option><option value='Imaduwa'>Imaduwa</option><option value='Karandeniya'>Karandeniya</option><option value='Koggala'>Koggala</option><option value='Kosgoda'>Kosgoda</option><option value='Mapalagama'>Mapalagama</option><option value='Nagoda'>Nagoda</option><option value='Neluwa'>Neluwa</option><option value='Pitigala'>Pitigala</option><option value='Rathgama'>Rathgama</option><option value='Thawalama'>Thawalama</option><option value='Udugama'>Udugama</option><option value='Uragasmanhandiya'>Uragasmanhandiya</option><option value='Wanduramba'>Wanduramba</option><option value='Yakkalamulla'>Yakkalamulla</option>");
                } 
                else if (val == "Matara") {
                    $("#cityi").html("<option value=''></option><option value='Matara'>Matara</option><option value='Weligama'>Weligama</option><option value='Weligama'>Weligama</option><option value='Akuressa'>Akuressa</option><option value='Athuraliya'>Athuraliya</option><option value='Devinuwara'>Devinuwara</option><option value='Dickwella'>Dickwella</option><option value='Hakmana'>Hakmana</option><option value='Kamburupitiya'>Kamburupitiya</option><option value='Kirinda'>Kirinda</option><option value='Kotapola'>Kotapola</option><option value='Malimbada'>Malimbada</option><option value='Mulatiyana'>Mulatiyana</option><option value='Pasgoda'>Pasgoda</option><option value='Pitabeddara'>Pitabeddara</option><option value='Thihagoda'>Thihagoda</option><option value='Welipitiya'>Welipitiya</option>");
                }
                 else if (val == "Kandy") {
                    $("#cityi").html("<option value=''></option><option value='Kandy'>Kandy</option><option value='Gampola'>Gampola</option><option value='Nawalapitiya'>Nawalapitiya</option><option value='Harispattuwa'>Harispattuwa</option><option value='Kadugannawa'>Kadugannawa</option><option value='Akurana'>Akurana</option><option value='Delthota'>Delthota</option><option value='Doluwa'>Doluwa</option><option value='Ganga Ihala Korale'>Ganga Ihala Korale</option><option value='Hatharaliyadda'>Hatharaliyadda</option><option value='Kundasale'>Kundasale</option><option value='Teldeniya'>Teldeniya - Medadumbara</option><option value='Minipe'>Minipe</option><option value='Panvila'>Panvila</option><option value='Pasbage korale'>Pasbage Korale</option><option value='Pathadumbara'>Pathadumbara</option><option value='Pathahewaheta'>Pathahewaheta</option><option value='Poojapitiya'>Poojapitiya</option><option value='Thumpane'>Thumpane</option><option value='Udapalatha'>Udapalatha</option><option value='Ududumbara'>Ududumbara</option><option value='Udunuwara'>Udunuwara</option><option value='Yatinuwara'>Yatinuwara</option>");
                }
                 else if (val == "Ratnapura") {
                    $("#cityi").html("<option value=''></option><option value='Embilipitiya'>Embilipitiya</option><option value='Balangoda'>Balangoda</option><option value='Ratnapura'>Ratnapura</option><option value='Eheliyagoda'>Eheliyagoda</option><option value='Pelmadulla'>Pelmadulla</option><option value='Kuruwita'>Kuruwita</option><option value='Imbulpe'>Imbulpe</option><option value='Godakawela'>Godakawela</option><option value='Kahawatta'>Kahawatta</option><option value='Rakwana'>Rakwana</option><option value='Weligepola'>Weligepola</option><option value='Nivitigala'>Nivitigala</option><option value='Ayagama'>Ayagama</option><option value='Kalawana'>Kalawana</option><option value='Kolonne'>Kolonne</option><option value='Panamure'>Panamure</option><option value='Pohorabawa'>Pohorabawa</option><option value='Opanayaka'>Opanayaka</option>");
                }
                 else if (val == "Matale") {
                    $("#cityi").html("<option value=''></option><option value='Matale'>Matale</option><option value='Dambulla'>Dambulla</option><option value='Galewela'>Galewela</option><option value='Naula'>Naula</option><option value='Pallepola'>Pallepola</option><option value='Rattota'>Rattota</option><option value='Ukuwela'>Ukuwela</option><option value='Gammaduwa'>Gammaduwa</option><option value='Inamaluwa'>Inamaluwa</option><option value='Kaikawala'>Kaikawala</option><option value='Kibissa'>Kibissa</option><option value='Laggala'>Laggala</option><option value='Madawala'>Madawala</option><option value='Nalanda'>Nalanda</option><option value='Palapathwela'>Palapathwela</option><option value='Sigiriya'>Sigiriya</option><option value='Wahacotte'>Wahakotte</option><option value='Yatawatta'>Yatawatta</option>");
                }
                else if (val == "Anuradhapura") {
                    $("#cityi").html("<option value=''></option><option value='Anuradhapura'>Anuradhapura</option><option value='Bulnewa'>Bulnewa</option><option value='Eppawala'>Eppawala</option><option value='Galenbindunuwewa'>Galenbindunuwewa</option><option value='Galnewa'>Galnewa</option><option value='Ganewalpola'>Ganewalpola</option><option value='Habarana'>Habarana</option><option value='Horowupotana'>Horowpotana</option><option value='Kahatagasdigiliya'>Kahatagasdigiliya</option><option value='Kebitigollawa'>Kebitigollawa</option><option value='Kekirawa'>Kekirawa</option><option value='Konapathirawa'>Konapathirawa</option><option value='Konwewa'>Konwewa</option><option value='Madatugama'>Madatugama</option><option value='Mahailuppallama'>Mahailuppalama</option><option value='Maradankadawala'>Maradankadawala</option><option value='Medawachchiya'>Medawachchiya</option><option value='Mihintale'>Mihintale</option><option value='Nochchiyagama'>Nochchiyagama</option><option value='Padawiya'>Padawiya</option><option value='Palugaswewa'>Palugaswewa</option><option value='Ranbewa'>Ranbewa</option><option value='Seeppukulama'>Seeppukulama</option><option value='Talawa'>Talawa</option><option value='Tambuttegama'>Tambuttegama</option><option value='Thirapanne'>Thirapanne</option><option value='Yakalla'>Yakalla</option>");
                }
                else if (val == "Badulla") {
                    $("#cityi").html("<option value=''></option><option value='Badulla'>Badulla</option><option value='Bandarawela'>Bandarawela</option><option value='Haputale'>Haputale</option><option value='Hali-Ela'>Hali-Ela</option><option value='Mahiyanganaya'>Mahiyanganaya</option><option value='Passara'>Passara</option><option value='Welimada'>Welimada</option><option value='Wiyaluwa'>Wiyaluwa</option><option value='Diyatalawa'>Diyatalawa</option><option value='Ella'>Ella</option><option value='Haldummulla'>Haldummulla</option><option value='Beragala'>Beragala</option><option value='Kandaketiya'>Kandaketiya</option><option value='Meegahakivula'>Meegahalivula</option><option value='Lunugala'>Lunugala</option><option value='Tennapanguwa'>Tennapanguwa</option>");
                }
                else if (val == "Monaragala") {
                    $("#cityi").html("<option value=''></option><option value='Monaragala'>Monaragala</option><option value='Bibile'>Bibile</option><option value='Wellawaya'>Wellawaya</option><option value='Kataragama'>Kataragama</option><option value='Siyambalanduwa'>Siyambalanduwa</option><option value='Buttala'>Buttala</option><option value='Tanamalvila'>Tanamalvila</option><option value='Badalkumbura'>Badalkumbura</option><option value='Madulla'>Madulla</option><option value='Okkampitiya'>Okkampitiya</option><option value='Medagama'>Medagama</option><option value='Sevanagala'>Sevanagala</option>");
                }
                else if (val == "Kurunegala") {
                    $("#cityi").html("<option value=''></option><option value='Kurunegala'>Kurunegala</option><option value='Narammala'>Narammala</option><option value='Wariyapola'>Wariyapola</option><option value='Nikaweratiya'>Nikaweratiya</option><option value='Pannala'>Pannala</option><option value='Galgamuva'>Galgamuava</option><option value='Polgahawela'>Polgahawela</option><option value='Maho'>Maho</option><option value='Alawwa'>Alawwa</option><option value='Ibbagamuwa'>Ibbagamuwa</option><option value='Giriulla'>Giriulla</option><option value='Hiripitiya'>Hiripitiya</option><option value='Dandagamuwa'>Dandagamuwa</option><option value='Dambadeniya'>Dambadeniya</option><option value='Melsiripura'>Melsiripura</option><option value='Hettipola'>Hettipola</option><option value='Katupotha'>Katupotha</option><option value='Potuhera'>Potuhera</option><option value='Mawathagama'>Mawathagama</option><option value='Yapahuwa'>Yapahuwa</option><option value='Pannawa'>Pannawa</option>");
                }
                else if (val == "Ampara") {
                    $("#cityi").html("<option value=''></option><option value='Ampara'>Ampara</option><option value='Addalaichchenai'>Addalaichchenai</option><option value='Akkaraipattu'>Akkaraipattu</option><option value='Alayadiwembu'>Alayadiwembu</option><option value='Damana'>Damana</option><option value='Galgamuva'>Galgamuva</option><option value='Polgahawela'>Polgahawela</option><option value='Maho'>Maho</option><option value='Dehiattakandiya'>Dehiattakandiya</option><option value='Irakkamam'>Irakkamam</option><option value='Kalmunai'>Kalmunai</option><option value='Karaitivu'>Karaitivu</option><option value='Lahugala'>Lahugala</option><option value='Maha Oya'>Maha Oya</option><option value='Namal Oya'>Namal Oya</option><option value='Navithanveli'>Navithanveli</option><option value='Nintavur'>Nintavur</option><option value='Padiyatalawa'>Padiyatalawa</option><option value='Pottuvil'>Pottuvil</option><option value='Sammanthurai'>Sammanthurai</option><option value='Thirukkovil'>Thirukkovil</option><option value='Uhana'>Uhana</option>");
                }
                else if (val == "Batticaloa") {
                    $("#cityi").html("<option value=''></option><option value='Eravurpattu'>Eravurpattu</option><option value='Kattankudy'>Kattankudy</option><option value='Koralaipattu'>Koralaipattu</option><option value='Manmunai'>Manmunai</option><option value='Manmunaipattu'>Damana</option><option value='Porativupattu'>Poratiupattu</option>");
                }
                else if (val == "Hambantota") {
                    $("#cityi").html("<option value=''></option><option value='Hambantota'>Hambantota</option><option value='Tangalle'>Tangalle</option><option value='Ambalantota'>Ambalantota</option><option value='Beliatta'>Beliatta</option><option value='Tissamaharama'>Tissamaharama</option><option value='Middeniya'>Middeniya</option><option value='Angunukolapelessa'>Angunukolapelessa</option><option value='Walasmulla'>Walasmulla</option><option value='Weeraketiya'>Weeraketiya</option>");
                }
                else if (val == "Jaffna") {
                    $("#cityi").html("<option value=''></option><option value='Jaffna'>Jaffna</option><option value='Kayts'>Kayts</option><option value='Velanai'>Velanai</option><option value='Karainagar'>Karainagar</option><option value='Nallur'>Nallur</option><option value='Chavakachcheri'>Chavakachcheri</option><option value='Muruthankerny'>Muruthankerny</option><option value='Point Pedro'>Point Pedro</option><option value='Karaveddy'>Karaveddy</option><option value='Kopay'>Kopay</option><option value='Tellippalai'>Tellippalai</option><option value='Uduvil'>Uduvil</option><option value='Sandilipay'>Sandilipay</option><option value='Chankanai'>Chankanai</option>");
                }
                else if (val == "Kalutara") {
                    $("#cityi").html("<option value=''></option><option value='Kalutara'>Kalutara</option><option value='Agalawatta'>Agalawatta</option><option value='Bandaragama'>Bandaragama</option><option value='Beruwala'>Beruwala</option><option value='Bulathsinhala'>Bulathsinhala</option><option value='Dodangoda'>Dodangoda</option><option value='Horana'>Horana</option><option value='Ingiriya'>Ingiriya</option><option value='Madurawela'>Madurawela</option><option value='Matugama'>Madatugama</option><option value='Millaniya'>Millaniya</option><option value='Palindanuwara'>Palindanuwara</option><option value='Panadura'>Panadura</option><option value='Walallawita'>Walallawita</option>");
                }
                else if (val == "Kegalle") {
                    $("#cityi").html("<option value=''></option><option value='Kegalle'>Kegalle</option><option value='Ambepussa'>Ambepussa</option><option value='Aranayaka'>Aranayaka</option><option value='Bulathkohupitiya'>Bulathkohupitiya</option><option value='Dehiovita'>Dehiovita</option><option value='Deraniyagala'>Deraniyagala</option><option value='Galigamuwa'>Galigamuwa</option><option value='Hemmathagama'>Hemmathagama</option><option value='Karawanella'>Karawanella</option><option value='Kitulgala'>Kitulgala</option><option value='Kotiyakumbura'>Kotiyakumbura</option><option value='Mawanella'>Mawanella</option><option value='Rambukkana'>Rambukkana</option><option value='Ruwanwella'>Ruwanwella</option><option value='Thalgaspitiya'>Thalgaspitiya</option><option value='Warakapola'>Warakapola</option><option value='Yatiyanthota'>Yatiyanthota</option>");
                }
                else if (val == "Kilinochchi") {
                    $("#cityi").html("<option value=''></option><option value='Kilinochchi'>Kilinochchi</option><option value='Pallai'>Pallai</option><option value='Poonakary'>Poonakary</option>");
                }
                else if (val == "Mannar") {
                    $("#cityi").html("<option value=''></option><option value='Mannar'>Mannar</option><option value='Madhu'>Madhu</option><option value='Adampan'>Adampan</option><option value='Chilawathurai'>Chilawathurai</option><option value='Nanaddan'>Nanaddan</option>");
                }
                else if (val == "Nuwara Eliya") {
                    $("#cityi").html("<option value=''></option><option value='Nuwara Eliya'>Nuwara Eliya</option><option value='Hapugastalawa'>Hapugastalawa</option><option value='Agrapatana'>Agrapatana</option><option value='Ambewela'>Ambewela</option><option value='Bogawanthalawa'>Bogawanthalawa</option><option value='Bopattalawa'>Bopattalawa</option><option value='Dayagama Bazaar'>Dayagama Bazaar</option><option value='Ginigathhena'>Ginigathhena</option><option value='Haggala'>Haggala</option><option value='Hatton'>Hatton</option><option value='Kotagala'>Kotagala</option><option value='Kotmale'>Kotmale</option><option value='Labukele'>Labukele</option><option value='Laxapana'>Laxapana</option><option value='Talawakele'>Talawakele</option><option value='Maskeliya'>Maskeliya</option><option value='Nanuoya'>Nanuoya</option><option value='Padiyapelella'>Padiyapelella</option><option value='Ramboda'>Ramboda</option><option value='Ragala'>Ragala</option><option value='Rozella'>Rozella</option><option value='Udapussallawa'>Udapussallawa</option><option value='Walapane'>Walapane</option><option value='Watawala'>Watawala</option>");
                }
                else if (val == "Polonnaruwa") {
                    $("#cityi").html("<option value=''></option><option value='Polonnaruwa'>Polonnaruwa</option><option value='Hingurakgoda'>Hingurakgoda</option><option value='Minneriya'>Minneriya</option><option value='Bakamuna'>Bakamuna</option><option value='Aragalanwila'>Araganwila</option><option value='Medirigiriya'>Medirigiriya</option><option value='Giritale'>Giritale</option><option value='Elahera'>Elahera</option><option value='Jayanthipura'>Jayanthipura</option><option value='Galamuna'>Galamuna</option><option value='Lankapura'>Lankapura</option><option value='Sungawila'>Sungawila</option><option value='Manampitiya'>Manampitiya</option><option value='Welikanda'>Welikanda</option><option value='Dimbulagala'>Dimbulagala</option>");
                }
                else if (val == "Puttalam") {
                    $("#cityi").html("<option value=''></option><option value='Puttalam'>Puttalam</option><option value='Wennappuwa'>Wennappuwa</option><option value='Dankotuwa'>Dankotuwa</option><option value='Anamaduwa'>Anamaduwa</option><option value='Marawila'>Marawila</option><option value='Madampe'>Madampe</option><option value='Kalpitiya'>Kalpitiya</option><option value='Nattandiya'>Nattandiya</option><option value='Battuluoya'>Battuluoya</option><option value='Mundel'>Mundel</option><option value='Mahawewa'>Mahawewa</option><option value='Palavi'>Palavi</option><option value='Thillaiyadi'>Thillaiyadi</option><option value='Eluvankulam'>Eluvankulam</option><option value='Nuraicholai'>Nuraicholai</option>");
                }
                else if (val == "Trincomalee") {
                    $("#cityi").html("<option value=''></option><option value='Gomarankadawala'>Gomarankadawala</option><option value='Kantalai'>Kantalai</option><option value='Kinniya'>Kinniya</option><option value='Kuchchaweli'>Kuchchaweli</option><option value='Morawewa'>Morawewa</option><option value='Muttur'>Muttur</option><option value='Padavi Siripura'>Padavi Siripura</option><option value='Seruvila'>Seruvila</option><option value='Thampalakamam'>Thampalakamam</option><option value='Verugul'>Verugul</option>");
                }
                else if (val == "Vavuniya") {
                    $("#cityi").html("<option value=''></option><option value='Vavuniya'>Vavuniya</option><option value='Nedunkeni'>Nedunkeni</option><option value='Cheddikulam'>Cheddikulam</option>");
                }
                else if (val == "Mullaitivu") {
                    $("#cityi").html("<option value=''></option><option value='Mullaitivu'>Mullaitivu</option><option value='Pandiyakulam'>Pandiyakulam</option><option value='Oddusuddan'>Oddusuddan</option><option value='Puthukkudiyiruppu'>Puthukkudiyiruppu</option><option value='Ehatugaswewa'>Ehatugaswewa</option>");
                }


            });
        });